// Help generated by ChatGPT

const searchInput = document.getElementById("search-input");
searchInput.addEventListener("keyup", function (event) {
    if (event.keyCode === 13) {
        filterElements();
    }
});

function filterElements() {
    const searchValue = searchInput.value.toLowerCase();
    const elements = document.getElementsByClassName("element");
    Array.from(elements).forEach(function(element) {
        if (element.getAttribute("data-name").toLowerCase().includes(searchValue)) {
            element.style.display = "block";
        } else {
            element.style.display = "none";
        }
    });
}

